In [2]:
import numpy as np

array1 = np.array(
    [
        [
           [2,2,2], [3,3,3], [1,1,1] 
        ],
        [
            [1,2,3], [4,5,6], [2,2,2]
        ],
        [
            [1,1,1], [7,7,7], [3,3,3]
        ]
    ])
array2 = np.array([2,2,2])

print(array1.shape)
print(array1 + 2)

(3, 3, 3)
[[[4 4 4]
  [5 5 5]
  [3 3 3]]

 [[3 4 5]
  [6 7 8]
  [4 4 4]]

 [[3 3 3]
  [9 9 9]
  [5 5 5]]]
